name: Employee Validation

on:
  push:
    branches:
      - main

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install pandas

      - name: Validate Employee CSV
        run: python python/validate.py
